language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  global:
  - PINS="ke:https://github.com/dinosaure/ke.git" 
  matrix:
  - PACKAGE="encore" OCAML_VERSION=4.07 TESTS=true
  - PACKAGE="encore" OCAML_VERSION=4.08 TESTS=true
  - PACKAGE="encore" OCAML_VERSION=4.09 TESTS=true
